import { Inter } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NextJS Template",
  description: "Generated by Ar Rafi Uddin",
};

export default function RootLayout({ children }) {
  return (
    <>
     <html lang="en">
      <body className={`${inter.className} flex flex-col justify-between min-h-screen`}>
        <div className="">
        <Navbar />
        <div className="">{children}</div>
        </div>
        <Footer />
      </body>
      </html>
    </>
    
  );
}
